### ISSUE TITLE
More checks for pyproject.toml files

### ISSUE THREAD

**Issue by mondeja** [mondeja/project-config-styles#21]
- [x] Check that at least one object is present in `tool.poetry.packages` and have a `from = "src"` configuration. Also, check that the folder *src/* exists (done in https://github.com/mondeja/project-config-styles/commit/30d90036be07a0a3df36a109ab24ab82e32481af):
   ```toml
   [[tool.poetry.packages]]
   include = "package_name"
   from = "src"
   ```
- [x] Check that the poetry build system is configured (done in https://github.com/mondeja/project-config-styles/commit/833f11928cad69ff48545ec29f2e7484c942637c):
   ```toml
   [build-system]
   requires = ["poetry-core>=1.0.0"]
   build-backend = "poetry.core.masonry.api"
   ```
