### ISSUE TITLE
Add `md2po2md` style

### ISSUE THREAD

**Issue by mondeja** [mondeja/project-config-styles#37]
Add a `md2po2md` pre-commit hook as:

```yaml
  - repo: https://github.com/mondeja/mdpo
    rev: v1.0.3
    hooks:
      - id: md2po2md
        files: ^README\.md
        args:
          - -l
          - es
          - -l
          - fr
          - -o
          - locale/{lang}
          - --no-location
 ```
