### ISSUE TITLE
Linting for the setup.py file

### ISSUE THREAD

**Issue by mondeja** [mondeja/project-config-styles#45]
Needs https://github.com/mondeja/project-config/issues/155 or https://github.com/mondeja/project-config/issues/156

Must match a template like:

```python
"""Installation using setup.py is no longer supported.
Use `pip install .` instead.
"""

import sys

from setuptools import setup

sys.exit(__doc__)

# Fake reference so GitHub still considers it a real package
# for statistics purposes:
setup(
    name="{rootdir_name()}",
)
```

- [ ] `sys.exit(__doc__)` must exist
- [ ] The first, second and third line must be like in the template.
- [ ] Imports must exist
- [ ] `setup(` line must exist
- [ ] `    name="{rootdir_name()}",` line must exist where `rootdir_name()` is the function that returns the root directory name in **project-config**.
- [ ] Flakeheaven must include some exceptions for *setup.py* in *pyproject.toml*:
   ```toml
   [tool.flakeheaven.exceptions."setup.py"]
   flake8-docstrings = ["-D205"]
   flake8-no-pep420 = ["-INP001"]
   ```
