### ISSUE TITLE
Github Actions versions updating

### ISSUE THREAD

**Issue by mondeja** [mondeja/project-config-styles#87]
## Deprecated actions versions

Node v12 Github Actions are deprecated since September 22, 2022. See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

- `actions/checkout` must use at least `v3`
- `actions/setup-python` must use at least `v4`
- `pre-commit/action` must use at least `v3.0.0`
- `actions/setup-node` must use at least `v3`
- `actions/cache` must use at least `v3`
- `actions/download-artifact` must use at least `v3`
- `actions/upload-artifact` must use at least `v3`

#### 1) Dependabot dependency updates just for Github Actions

A *.github/dependabot.yml* file with the content:

```yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "monthly"
 ```

> Note that I'm not using any other tool for dependency updating. There is a Github Actions workflow to update pre-commit hooks in Python projects. The documentation and direct dependencies are manually bumped when new versions of the library are released, if needed.

The problem with this solution is that dependabot does not support a scheduled datetime to run. I would like to execute this updater twice a year, in June and January or once a year in June. I don't have the time to review pull requests with dependency updates every month.

<details>
  <summary>What about Renovate?</summary>
I don't want to go with Renovate because in the past I've experienced bad releasing practices causing a lot of spam just to show new Renovate's features.
</details>

#### 2) Auto merge dependabot PRs + master branch rebasing + scheduled workflow to merge with master

> This idea is taken from https://www.hacksoft.io/blog/managing-dependencies-with-github-dependabot-and-actions

Just add Dependabot monthly targetting a new branch `dependencies` and configure automerging of Dependabot's PRs in a new workflow (see [Enable auto-merge on a pull request](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions?learn=dependency_version_updates&learnProduct=code-security#enable-auto-merge-on-a-pull-request)).

```yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "monthly"
    target-branch: "dependencies"
```

Add other workflow to rebase with master:

```yml
name: Automatic Rebase
on:
  push:
    branches:
      - master

jobs:
  rebase:
    name: Rebase `dependencies` with `master`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
          ref: dependencies
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rebase origin/master
          git push origin dependencies --force
```

And schedule other third workflow to merge dependencies into master.

This solution is a bit complex as it requires 3 new workflows. Also, the information about updated dependencies would be lost in the scheduled workflow. Is not a great solution but better than 1).

#### 3) Exist some library to make this update?

Exists an action to update Github Actions versions, check https://github.com/saadmk11/github-actions-version-updater. Needs a PAT with `repo` and `workflow` permissions to be added to the secrets of the repository.
